
on: [push]
#  push:
#    tags: '**'

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: install prerequisites
        run: sudo apt-get update && sudo apt-get -y install debhelper devscripts libevent-dev
      - name: build .deb
        run: sudo DEBUILD_DPKG_BUILDPACKAGE_OPTS="-r'fakeroot --faked faked-tcp' -us -uc" DEBUILD_LINTIAN_OPTS="-i -I --show-overrides" sudo debuild --no-conf -us -uc

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: build executables
        run: |
          .\set-msvc-path.ps1
          nmake clean download build
