
on: [push]
#  push:
#    tags: '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
        path: build
      - name: install prerequisites
        run: sudo apt-get update && sudo apt-get -y install debhelper devscripts libevent-dev
      - name: build .deb
        run: sudo (cd build && DEBUILD_DPKG_BUILDPACKAGE_OPTS="-r'fakeroot --faked faked-tcp' -us -uc" DEBUILD_LINTIAN_OPTS="-i -I --show-overrides" sudo debuild --no-conf -us -uc)
