
name: Update config + Trigger Release

# This trigger updates the repo's configuration with new download URLs and version number,
#   and then starts the build + release process.
#
# Syntax for invoking this trigger:
#
# USERNAME=<name> \
# PERSONAL_ACCESS_TOKEN=<token> \
# ORGANIZATION=<org> \
# REPOSITORY=<repo> \
# VASM_RELEASE_URL=<source code URL> \
# VASM_RELEASE_VERSION=<version> \
# bash -c 'curl -XPOST -u $USERNAME:$PERSONAL_ACCESS_TOKEN \
#    -H "Accept: application/vnd.github.everest-preview+json" \
#    -H "Content-Type: application/json" \
#    "https://api.github.com/repos/$ORGANIZATION/$REPOSITORY/dispatches" \
#    --data "{\"event_type\" : \"update-config-and-trigger-release\", \
#             \"client_payload\" : { \"vasm_release_url\" : \"$VASM_RELEASE_URL\", \
#                                    \"vasm_release_version\" : \"$VASM_RELEASE_VERSION\" } }"'

on:
  repository_dispatch:
    types: [update-config-and-trigger-release]

jobs:
  update-config-and-trigger-release:
    name: Update config and trigger release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          # Use a different token than GITHUB_TOKEN for accessing the repository
          # The non-default token will make the push operations trigger new workflow runs in build.yml
          token: "${{ secrets.THIS_REPO__PUSH__TOKEN }}"
      - name: Update config
        run: NEW_VASM_RELEASE_URL=${{ github.event.client_payload.vasm_release_url }} NEW_VASM_RELEASE_VERSION=${{ github.event.client_payload.vasm_release_version }} make update-config
      - name: Trigger new release
        run: make release
